### PR TITLE
Moving 2017GameLab to Akl-game-lab

### PR DESCRIPTION
**Pull request by whydah12**
There has been significant changes made to one of the files. The way inwhich we authenticate users and retrieve data from exercise.com should now be more robust.\
Credit to hydroflax, see commit notes for details

### CODE REVIEW

**Comment by SarenCurrie** [comment]
You've been busy....

**Comment by whydah12** [comment]
We have. Thoughts?
I see we are failing a check. We didn't have any checks on the other repo. Is it still relevant after the changes?

**Comment by SarenCurrie** [comment]
I think the check that’s failing is the tests. Run `npm test` to see if the tests still pass. Chances are they’ve been superseded by what you’ve been doing. If I recall correctly the CI also runs a linter. I’d recommend turning that off and migrating to ESLint if you get the chance.

**Comment by bladesaunterer** [comment]
Currently tidying up pull request to meet acceptance criteria

**Comment by bladesaunterer** [comment]
Merging 2017GameLab into a new branch of this repository

**Pull request closed without merging**
